defaults:
  - env: cntree
  - _self_

env:
  node_encoding_corr: 0.
  n_envs: 1000  # To make test dataset
  branching_prob: 1.0  # To make test dataset
  horizon: 1600  # To make test dataset

from_origin: True

wandb:
  project: cntree

storage_dir: /n/holylfs06/LABS/krajan_lab/Lab/cfang/icl-maze