defaults:
  - env: cntree #tree
  - _self_

#env:
#  n_envs: 300000 #1000
#  branching_prob: 0.9 #1.0
#  horizon: 800 #1600

from_origin: True

wandb:
  project: cntree

storage_dir: /n/holylfs06/LABS/krajan_lab/Lab/cfang/icl-maze