defaults:
  - env: darkroom
  - _self_

env:
  node_encoding_corr: 0.0

wandb:
  project: darkroom_simple

from_origin: False  # Not relevant for darkroom

storage_dir: /n/holylfs06/LABS/krajan_lab/Lab/cfang/icl-maze