defaults:
  - env: tree
  - _self_

env:
  n_envs: 300000
  branching_prob: 0.85

from_origin: False

wandb:
  project: lazyload

storage_dir: /n/holylfs06/LABS/krajan_lab/Lab/cfang/icl-maze
#storage_dir: /n/holylabs/LABS/krajan_lab/Lab/cfang/icl-maze