defaults:
  - model: transformer
  - env: darkroom
  - optimizer: default  # For finding the relevant trained model
  - _self_

wandb:
  project: "darkroom"

seed: 0
epoch: -1
H: -1
n_eval: 100
storage_dir: /n/holylabs/LABS/krajan_lab/Lab/cfang/icl-maze