defaults:
  - model: dqn
  - env: tree_dqn
  - optimizer: dqn
  - _self_

wandb:
  project: dqn_full

n_eval_envs: 50 # (~per-mouse, each environment contains a different interaction history)
test_horizon: 400  # (horizon for each evaluation episode)
n_eval_episodes: 40 # (per environment)
storage_dir: /n/holylfs06/LABS/krajan_lab/Lab/cfang/icl-maze
#storage_dir: /n/holylabs/LABS/krajan_lab/Lab/cfang/icl-maze

override_eval_dataset_path: /n/holylfs06/LABS/krajan_lab/Lab/cfang/icl-maze/lazyload/tree_layers7_bprob1.0_envs600000_H1600_explore/datasets/eval.h5
override_params:
  - branching_prob: 1.
