defaults:
  - model: transformer
  - env: darkroom
  - optimizer: default  # For finding the relevant trained model
  - _self_

wandb:
  project: darkroom_NoPosEmbedding

seed: 0
epoch: best
H: -1
n_eval: 20
storage_dir: /n/holylabs/LABS/krajan_lab/Lab/cfang/icl-maze