defaults:
  - model: transformer_end_query
  - env: tree
  - optimizer: default  # For finding the relevant trained model
  - _self_

wandb:
  project: full7

seed: 0
epoch: best
n_eval_envs: 30
test_horizon: 800  # (horizon for each evaluation episode)

# Eval-specific parameters
offline_eval_episodes: 50 # (per environment)
online_eps_in_context: 1 # (number of episodes to keep in context)
online_eval_episodes: 40 # (number of sequential episodes to run)

storage_dir: /n/holylfs06/LABS/krajan_lab/Lab/cfang/icl-maze
#storage_dir: /n/holylabs/LABS/krajan_lab/Lab/cfang/icl-maze
