defaults:
  - model: transformer_end_query
  - env: darkroom
  - optimizer: default
  - _self_

model:
  train_query_every: 10
  n_embd: 512
  n_layer: 4
  dropout: 0.

env:
  node_encoding_corr: 0.25
  maze_dim: 8
  horizon: 250

optimizer:
  batch_size: 512
  num_epochs: 25

wandb:
  project: darkroom_simple 

storage_dir: /n/holylfs06/LABS/krajan_lab/Lab/cfang/icl-maze
override_dataset_dir: null
