defaults:
  - model: linear_transformer
  - env: tree
  - optimizer: default
  - _self_

wandb:
  project: 7layer

optimizer:
  lr: 1e-4
  batch_size: 128
  num_epochs: 100
  use_scheduler: False

env:
  n_envs: 300000
  store_gpu: True

seed: 0
storage_dir: /n/holylfs06/LABS/krajan_lab/Lab/cfang/icl-maze