defaults:
  - model: transformer_end_query
  - env: cntree
  - optimizer: default
  - _self_

model:
  dropout: 0.2
  #train_shuffle_memories: true
  #initialization_seed: 4

wandb:
  project: tree_maze

storage_dir: /n/holylfs06/LABS/krajan_lab/Lab/cfang/icl-maze
#override_dataset_dir: null
override_dataset_dir: tree_maze
