defaults:
  - model: transformer_end_query
  - env: cntree
  - optimizer: default
  - _self_

wandb:
  project: tree_maze_bigger_models

storage_dir: /n/holylfs06/LABS/krajan_lab/Lab/cfang/icl-maze
#override_dataset_dir: null
override_dataset_dir: tree_maze
