defaults:
  - model: transformer_end_query
  - env: cntree
  - optimizer: default
  - _self_

optimizer:
  num_epochs: 2000

wandb:
  project: tree_maze_more_training

storage_dir: /n/holylfs06/LABS/krajan_lab/Lab/cfang/icl-maze
#override_dataset_dir: null
override_dataset_dir: tree_maze
