defaults:
  - model: transformer_end_query
  - env: cntree
  - optimizer: default
  - _self_

optimizer:
  lr: 1e-5

env:
  node_encoding_corr: 0.25

wandb:
  project: cntree

seed: 0
storage_dir: /n/holylfs06/LABS/krajan_lab/Lab/cfang/icl-maze
override_dataset_dir: null #/n/holylfs06/LABS/krajan_lab/Lab/cfang/icl-maze/datasets