defaults:
  - model: transformer_end_query
  - env: tree
  - optimizer: default
  - _self_

model:
  dropout: 0
  n_layer: 3

optimizer:
  lr: 1e-6

env:
  n_envs: 300000

wandb:
  project: random_tree

seed: 0
storage_dir: /n/holylfs06/LABS/krajan_lab/Lab/cfang/icl-maze
override_dataset_dir: null #/n/holylfs06/LABS/krajan_lab/Lab/cfang/icl-maze/datasets