defaults:
  - model: rnn
  - env: cntree
  - optimizer: rnn
  - _self_

env:
  node_encoding_corr: 0.25
  max_layers: 5

wandb:
  project: smaller_tree_maze

storage_dir: /n/holylfs06/LABS/krajan_lab/Lab/cfang/icl-maze
override_dataset_dir: null