defaults:
  - model: transformer_end_query
  - env: cntree
  - optimizer: default
  - _self_

model:
  n_layer: 4

optimizer:
  batch_size: 256

wandb:
  project: tree_maze

storage_dir: /n/holylfs06/LABS/krajan_lab/Lab/cfang/icl-maze
override_dataset_dir: null #/n/holylfs06/LABS/krajan_lab/Lab/cfang/icl-maze/datasets