defaults:
  - model: transformer_end_query
  - env: darkroom
  - optimizer: default
  - _self_

model:
  train_query_every: 5
  n_embd: 512
  n_layer: 3
  dropout: 0.

optimizer:
  batch_size: 1024
  num_epochs: 25
  lr: 0.0001

wandb:
  project: darkroom_simple 

storage_dir: /n/holylfs06/LABS/krajan_lab/Lab/cfang/icl-maze
override_dataset_dir: null
