defaults:
  - model: transformer_end_query
  - env: tree
  - optimizer: default
  - _self_

wandb:
  project: lazyload

model:
  _target_: src.models.transformer_end_query.FixedMemoryTransformer
  name: fixedmemory_transformer

#env:
#  n_envs: 300000
#  store_gpu: True

seed: 0
storage_dir: /n/holylfs06/LABS/krajan_lab/Lab/cfang/icl-maze