env: tree
n_envs: 300000
horizon: 800
max_layers: 7
branching_prob: 1.
node_encoding: random  #  If null, state_dim = 2. If random, state_dim = 10
state_dim: 10
action_dim: 4
store_gpu: False
rollin_type: explore

# For data creation and collection purposes
goal_total_seeds: 0  # Only used if branching_prob < 1
n_search_seeds: 0