env: tree
n_envs: 600000
horizon: 800
max_layers: 7
branching_prob: 0.9
node_encoding: random  #  If null, state_dim = 2. If random, state_dim = 10
state_dim: 10
action_dim: 4
store_gpu: False
rollin_type: explore